### ISSUE TITLE
Symbolic links on Windows

### ISSUE THREAD

**Issue by bkamins** [JuliaPackaging/BinaryProvider.jl#123]
This is speculative as I am not an expert here.

On my Win10 `unpack` fails because creation of symbolic links throws an error that is not caught.
Maybe on Win10 `ENV["BINARYPROVIDER_COPYDEREF"]` should be set to `"true"` by default on this platform as this solves the problem.

I am not sure if this is my local problem or a general problem for Win10.

**Comment by arnavs** [comment]
I'm seeing a different but related issues on Win10. In particular, when using the package (inside https://github.com/QuantEcon/InstantiateFromURL.jl), we initially get some `Warning: Creating symbolic links on Windows requires administrator privileges.` Nothing seems to break because of it, but it would be great if we could either fix or disable it, if only so that people don't worry. 

cc: @jlperla

**Comment by musm** [comment]
Yep I see this too

**Comment by jlperla** [comment]
Is there any way to swallow or turn off the warnings when including the package?

**Comment by arnavs** [comment]
(Note on the above, we've tried `@suppress` and friends from Suppressor.jl, but no luck)

**Comment by hhaensel** [comment]
This is related to #149, I filed PR #165 to suppress the message.
In order to troubleshout @bkamins issue, we would probably need an error log...
Maybe the issue is meanwhile solved?

**Comment by bkamins** [comment]
I do not run into this issue as it can be worked around on Win10 by running Julia in administrator mode.

@pszufe - do you remember installing which package on normal user mode triggers this error?

**Comment by hhaensel** [comment]
I think this is now solved with #166

**Comment by bkamins** [comment]
I will reopen the issue if I encounter this problem again.
