### ISSUE TITLE
MacOS doesn't delete old binaries when updating

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPackaging/BinaryProvider.jl#29]
Multiple reports which seem to be this same issue that users from the old Sundials on MacOS get both binaries when it updates, and that confuses BinaryProvider.jl

**Comment by staticfloat** [comment]
Can you explain this a little bit more?  What old binaries are not getting updated?  Binaries previously provided by BinaryProvider.jl?

**Comment by ChrisRackauckas** [comment]
No, binaries previously provided by BinDeps.

**Comment by staticfloat** [comment]
Yeah, I'm not sure there's much we can do here within BinaryProvider; it's definitely not going to delete files automatically; that's way too dangerous.  If the old binaries are deemed "okay" by the system (e.g. it can `dlopen()` them) it generally thinks they're okay.  I suppose we could come up with some kind of validation system, but I'd prefer not to if at all possible.  (The validation system would look something like what BinDeps has right now; e.g. you provide a callback to `LibraryProduct()` that gets called with the candidate library that has been found by the system, and if it returns `False` that library is not allowed to satisfy that `LibraryProduct`.

Alternatively, as I mentioned in the other issue, we could force a hash check on downloads so that only the latest binary published by a package is used, (as opposed to the current behavior of "any version will do") which would force a download of the newer stuff even if the old BinDeps stuff exists, due to the fact that the old BinDeps stuff doesn't have the right files downloaded.

However, I'm not entirely sure what would happen if the BinDeps stuff is sitting in the same directory as where BinaryProvider wants to put its stuff.  I think that unless `install()` is passed the `force` parameter, it's just going to refuse to overwrite files it doesn't know about.

**Comment by ChrisRackauckas** [comment]
https://discourse.julialang.org/t/has-mismatch-on-latest-sundials/9128/5

As mentioned here, we should consider putting warning for MacOS users when the hash mismatch comes up so that way they know about this issue.

**Comment by staticfloat** [comment]
The fix I just merged will overwrite previous tarballs that have been downloaded by `BinaryProvider`; that will fix [the issue reported here](https://github.com/JuliaDiffEq/Sundials.jl/issues/157#issue-298302067), and setting `force=true` within `install()` will overwrite any previous binaries that were installed into the package-local prefix.  (This is the default in newly generated `build.jl` files, and is also the case already in the Sundials `build.jl`)

So with that, I think this issue is closed.  A new `BinaryProvider` release is making its way through the METADATA.jl checks, and should be published later today.
